language: java
notifications:
  hipchat:
    rooms:
      secure: ZiSyGwuy09O35VDhaUUtAIg3Feqx1vcmustxIEGL32+W6Dbw/UjhLWXsQofgPN0EFXcwpe9R7IyolYECQGBPrh75ftgnRZ7NOYdli3bdcudhLFLeiOvtP57274BWx+rMAOA8sk4CDvV/keToqxJlZ2RLSBoWGK/qwjtu0oP/jizuZ1BiFvOSppW7pj189lCidJdoRwpnr2/Ee4j9A0iTSmWRztriwMvfvL1Euyr8PP8xVKgypKKXtOT9kcl22k8T9dl35ps/D/FK/qhGXJEFjpSo2a1XniaQiw5zNr1m4ACrt7lChyHeKZYRHZD7A706OxAdkgzch33OcIi5IFpH7QtEDGUhWclaA7j3D48w9cJ8SP5RNOoxQ/kKso7Q9EQ+6Ism6rGr6R62KWUbCTM2/+cntOVJ97nzL9GOLOOt+YFLbBjLyPMEdj0xrw+CSVtmfNzJ6rT6MeXbhwSvRm3mB31mDHBE0fmMdHvr6ZEo76b169QSfdR6C4Di5dENrsMzobiL83T6pPksHweTdoTFfyx3Wk9rkp2iwWrb8saZOKm9H9ZwFLRhNbU3stj6LVjtZJArf3aAwLFlIqgGWnDL2HH7O01lXFXtZyJ+licNMWasOyCV4uP75ZHMIA6/v9V5UNCUNTdhE7vHRJbWmXQz+WNb+OlNqQcv0mc3nFADXkQ=
    on_success: always
    on_failure: always
deploy:
  provider: releases
  api_key:
    secure: pTtpLyuK+U8TUDzSkf5J6w/xhGbDTdbWoFHqPrI0AceIbHMiNJADDNa721WneUHXJUNhjlPzZJdZ6u65GuSuMvtnkozHMEzZfDjV7NvbIEtUPhm/8qiALj5eZDtDFSwU6n0Pkf8+7slSswCPFbzKTcSQqoXyVew+/n7LmNGClchQIZwXRoZS3E3NuMbD9dOMKoIXHdPWfBFcYJjAUhI8UfM1Gmj1zXP64smLpLh7owE/lIMEuzUGS6Dis1PKeAL7hFdbuS9ggEbtwtCghzkPAfL2q8dXyboLAesXDRjpy7tuLfdil3l0VIB8bTKYkPSgz7p29bp44gI5Tbb8Ufel1j6YMWFILHe6rWcMBfrHVR4HRBistMqRKX9RCztvUmPqw0JwKVV2RJ530ud7lKlaTfAKY/0SSzEDjtSIXwIx0l6C0lnJRG5eqSi3C59wu8BwSySvdx//KnioCAgjUYgvcwhncc62xvd3/P9THj78fSsgEnzonyBTu3XxH0AANfZxZeZ43NamtO8EACShlspPrzFF48BHVAtqrZi49o2NoNW0Z9AvfxknHzpiV8kYl/QtTGx+L6Ci765uVHLNF2D+QBt7o/8/rxEAq0cx0wnM15katdCCfkZP42hjb2LUWM9QK6PZCn4YDiH6BXCdjPEPvCNXBrCo3T/78qGjWmu/d4I=
  file: 
    - "build/libs/xlr-rtcjazz-plugin-1.0.0.jar"
    - "rtc6.0.1jars.zip"
  skip_cleanup: true
  on:
    tags: true
    branch: master
    repo: xebialabs-community/xlr-rtcjazz-plugin
